"""Generic, device-agnostic workflow framework.

Business workflows and vendor adapters live outside this package. New
applications should compose those plugins around these stable framework
contracts.
"""

from .decisions import DecisionEngine, DecisionSubmission, DecisionValidationError
from .activity import (
    ActivityContext,
    ActivityDefinition,
    ActivityHandler,
    ActivityInvocation,
    ActivityProbe,
    ActivityReconciler,
    ActivityResult,
    ActivityStatus,
    ActivityVerifier,
    ExchangeSpec,
    GuardSpec,
    IdempotencyPolicy,
    MonitorSpec,
    ProgressReporter,
    VerificationSpec,
)
from .activity_executor import ActivityActionHandler, ActivityExecutionError, ActivityExecutor
from .orchestrator import (
    MemoryTaskRunStore,
    TaskOrchestrator,
    TaskPlan,
    TaskRun,
    TaskRunStatus,
    TaskRunStore,
    WorkflowNode,
)
from .dsl import WorkflowDslError, compile_workflow
from .events import Event, MemoryWorkflowEventStore, WorkflowEventStore
from .models import (
    ActionAttempt,
    ActionResult,
    ActionSpec,
    ActionStatus,
    DeviceStateSnapshot,
    DecisionPoint,
    Expectation,
    InteractionPolicy,
    Option,
    ProgressSnapshot,
    ReconcileClassification,
    ReconcileResult,
    ReconcilePolicy,
    RetryPolicy,
    RunStatus,
    StateNode,
    WorkflowDefinition,
    WorkflowRun,
)
from .plugins import (
    ActionHandler,
    ActionRegistry,
    ActivityRegistry,
    AdapterRegistry,
    DeviceAdapter,
    DeviceVendorAdapter,
    ReconcileRegistry,
    ReconcileProvider,
    WorkflowProvider,
    WorkflowRegistry,
)
from .runtime import MemoryWorkflowRunStore, WorkflowRuntime
from .resources import LeaseResourceCoordinator, ResourceCoordinator, ResourceLease, ResourceRequest
from .supervisor import ActionSupervisor, SupervisedActionResult
from .watchdog import Watchdog, WatchdogIncident
from .errors import ResourceConflictError

__all__ = [
    "ActivityContext",
    "ActivityDefinition",
    "ActivityActionHandler",
    "ActivityExecutionError",
    "ActivityExecutor",
    "ActivityHandler",
    "ActivityInvocation",
    "ActivityProbe",
    "ActivityRegistry",
    "ActivityReconciler",
    "ActivityResult",
    "ActivityStatus",
    "ActivityVerifier",
    "TaskOrchestrator",
    "MemoryTaskRunStore",
    "TaskPlan",
    "TaskRun",
    "TaskRunStatus",
    "TaskRunStore",
    "ActionAttempt",
    "ActionHandler",
    "ActionRegistry",
    "ActionResult",
    "ActionSpec",
    "ActionSupervisor",
    "ActionStatus",
    "AdapterRegistry",
    "DecisionEngine",
    "DecisionPoint",
    "DecisionSubmission",
    "DecisionValidationError",
    "DeviceAdapter",
    "DeviceVendorAdapter",
    "DeviceStateSnapshot",
    "Event",
    "ExchangeSpec",
    "Expectation",
    "GuardSpec",
    "IdempotencyPolicy",
    "InteractionPolicy",
    "MemoryWorkflowEventStore",
    "MemoryWorkflowRunStore",
    "MonitorSpec",
    "Option",
    "ProgressSnapshot",
    "ProgressReporter",
    "ReconcileClassification",
    "ReconcileProvider",
    "ReconcilePolicy",
    "ReconcileRegistry",
    "ReconcileResult",
    "RetryPolicy",
    "RunStatus",
    "StateNode",
    "SupervisedActionResult",
    "Watchdog",
    "WatchdogIncident",
    "WorkflowDefinition",
    "WorkflowDslError",
    "WorkflowEventStore",
    "WorkflowProvider",
    "WorkflowRegistry",
    "WorkflowRun",
    "WorkflowNode",
    "WorkflowRuntime",
    "LeaseResourceCoordinator",
    "ResourceCoordinator",
    "ResourceLease",
    "ResourceRequest",
    "VerificationSpec",
    "ResourceConflictError",
    "compile_workflow",
]
