"""UI-independent AI, approval, and audit facade for the desktop backend.

The service deliberately works with application services only.  It is therefore
usable by FastAPI, MCP, and other service clients without importing a desktop UI.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass
from pathlib import Path
import threading
import time
from typing import Any
from uuid import uuid4

from ..ai_device_ops import RiskLevel, classify_command_risk
from ..ai_gateway.skills import SkillLoadError, SkillRegistry
from ..device_mcp.audit import AuditLogger, redact_text
from ..terminal_orchestration import TerminalPlanError, build_batch_plan, parse_terminal_plan
from .desktop import DesktopApplication
from .errors import ResourceNotFoundError, UnsupportedOperationError
from .transfers import TerminalPlanExecutor


@dataclass(frozen=True, slots=True)
class AiPlan:
    objective: str
    summary: str
    actions: tuple[dict[str, Any], ...]
    warnings: tuple[str, ...] = ()


class AiApplicationService:
    """Deterministic AI boundary shared by UI, HTTP, and MCP adapters."""

    def __init__(
        self,
        desktop: DesktopApplication,
        *,
        audit_path: Path | None = None,
        approval_mode: str | None = None,
        terminal_executor: TerminalPlanExecutor | None = None,
        skill_registry: SkillRegistry | None = None,
        audit_max_bytes: int = 10 * 1024 * 1024,
        audit_backup_count: int = 5,
    ) -> None:
        self.desktop = desktop
        # AI/MCP requests are intentionally non-interactive.  The parameter is
        # accepted only to keep composition compatible with older launch config.
        del approval_mode
        self.approval_mode = "disabled"
        self.audit = AuditLogger(
            audit_path,
            max_bytes=audit_max_bytes,
            backup_count=audit_backup_count,
        )
        self._terminal_executor = terminal_executor
        self._skills = skill_registry or SkillRegistry()
        self._audit_entries: list[dict[str, Any]] = []
        self._results: dict[str, dict[str, Any]] = {}
        self._lock = threading.RLock()

    def plan(self, objective: str, *, selected_device_id: str = "") -> AiPlan:
        text = objective.strip()
        if not text:
            raise UnsupportedOperationError("An AI objective is required.")
        devices = list(self.desktop.devices.list_inventory().devices)
        device_id = selected_device_id or (devices[0].id if devices else "")
        actions: list[dict[str, Any]] = []
        warnings: list[str] = []
        lower = text.casefold()
        if not device_id:
            warnings.append("No device is available; select a device before execution.")
        if any(word in lower for word in ("upgrade", "换包", "升级")):
            actions.extend([
                self._action("open_session", "Open a terminal session", RiskLevel.LOW, device_id=device_id),
                self._action("package_upgrade", "Run guarded package upgrade", RiskLevel.FLOW, device_id=device_id),
            ])
        elif any(word in lower for word in ("version", "版本")):
            actions.extend([
                self._action("open_session", "Open a terminal session", RiskLevel.LOW, device_id=device_id),
                self._action("command", "Read device version", RiskLevel.LOW, device_id=device_id, command="display version"),
            ])
        else:
            actions.append(self._action("observe", "Inspect the selected device", RiskLevel.OBSERVE, device_id=device_id))
        return AiPlan(
            objective=text,
            summary="A deterministic, reviewable plan generated by the Python application service.",
            actions=tuple(actions),
            warnings=tuple(warnings),
        )

    async def execute_command(
        self,
        command: str,
        *,
        session_id: str,
        approval_token: str | None = None,
        source: str = "desktop-ui",
        idempotency_key: str | None = None,
    ) -> dict[str, Any]:
        normalized = command.strip()
        if not normalized:
            raise UnsupportedOperationError("A command is required.")
        session = self._session(session_id)
        action = self._action(
            "command",
            "Execute terminal command",
            classify_command_risk(normalized),
            device_id=session.device_id,
            session_id=session_id,
            command=normalized,
        )
        cached = self._cached(source, "command", idempotency_key)
        if cached is not None:
            return cached
        del approval_token
        await self.desktop.commands.send(session_id, normalized)
        await asyncio.sleep(0)
        log = self.desktop.sessions.read_log(session_id, 32_768)
        output = redact_text(log.content[-32_768:])
        result = self._store_result(
            "command",
            {
                "status": "success",
                "session_id": session_id,
                "device_id": session.device_id,
                "command": redact_text(normalized),
                "output": output,
            },
        )
        self.desktop.events.publish("ai.result.created", resource_id=result["result_id"], data={"result_id": result["result_id"], "kind": "command", "status": "success"})
        self._record_audit(tool="ai_execute_command", source=source, action=action, status=200)
        self._cache(source, "command", idempotency_key, result)
        return result

    async def execute_batch(
        self,
        commands: list[str],
        *,
        session_id: str,
        command_timeout_seconds: int = 30,
        approval_token: str | None = None,
        source: str = "desktop-ui",
        idempotency_key: str | None = None,
    ) -> dict[str, Any]:
        if not commands:
            raise UnsupportedOperationError("At least one command is required.")
        cached = self._cached(source, "batch", idempotency_key)
        if cached is not None:
            return cached
        session = self._session(session_id)
        normalized = [str(command).strip() for command in commands if str(command).strip()]
        action = self._action(
            "batch",
            "Execute terminal command batch",
            max((classify_command_risk(command) for command in normalized), default=RiskLevel.OBSERVE),
            device_id=session.device_id,
            session_id=session_id,
            command="\n".join(normalized),
            command_count=len(normalized),
        )
        del approval_token
        results: list[dict[str, Any]] = []
        for command in normalized:
            await self.desktop.commands.send(session_id, command)
            await asyncio.sleep(0)
            log = self.desktop.sessions.read_log(session_id, 32_768)
            results.append(self._store_result("command", {
                "status": "success",
                "session_id": session_id,
                "device_id": session.device_id,
                "command": redact_text(command),
                "output": redact_text(log.content[-32_768:]),
            }))
        payload = self._store_result("batch", {"status": "success", "session_id": session_id, "results": results, "command_count": len(results), "timeout_seconds": command_timeout_seconds})
        self._record_audit(tool="ai_execute_batch", source=source, action=action, status=200)
        self._cache(source, "batch", idempotency_key, payload)
        return payload

    async def execute_script(
        self,
        script: str,
        *,
        session_id: str,
        timeout_seconds: int = 30,
        source: str = "desktop-ui",
        idempotency_key: str | None = None,
    ) -> dict[str, Any]:
        commands = [line.strip() for line in script.splitlines() if line.strip()]
        return await self.execute_batch(
            commands,
            session_id=session_id,
            command_timeout_seconds=timeout_seconds,
            source=source,
            idempotency_key=idempotency_key,
        )

    def list_skills(self) -> list[dict[str, Any]]:
        return self._skills.list_skills()

    async def run_skill(
        self,
        skill_name: str,
        params: dict[str, Any],
        *,
        session_id: str,
        source: str = "desktop-ui",
        idempotency_key: str | None = None,
    ) -> dict[str, Any]:
        cached = self._cached(source, "skill", idempotency_key)
        if cached is not None:
            return cached
        session = self._session(session_id)
        try:
            plan = self._skills.instantiate_flow(skill_name, params)
        except SkillLoadError as exc:
            raise UnsupportedOperationError(str(exc), details={"code": exc.code}) from exc
        completed: set[str] = set()
        failed: set[str] = set()
        steps: list[dict[str, Any]] = []
        for step in plan.steps:
            if set(step.depends_on) & failed or set(step.depends_on) - completed:
                steps.append({"id": step.id, "status": "skipped", "output": "", "message": "Dependency was not completed."})
                failed.add(step.id)
                continue
            result = await self.run_terminal_plan(
                session_id=session_id,
                steps=[
                    {"type": "send", "text": step.command, "label": step.id},
                    {
                        "type": "expect",
                        "success": ["device_prompt"],
                        "failures": ["Error:", "Unrecognized command", "Unknown command"],
                        "timeout_seconds": step.timeout_seconds,
                        "label": step.id,
                    },
                ],
                total_timeout_seconds=step.timeout_seconds + 5,
                source=source,
                kind="skill_step",
            )
            output = self._result_output(result)
            if result.get("status") == "completed":
                completed.add(step.id)
                steps.append({"id": step.id, "status": "success", "output": output})
            else:
                failed.add(step.id)
                steps.append({"id": step.id, "status": "failed", "output": output, "error_code": result.get("error_code", "execution_failed")})
                break
        status = "success" if not failed else "failed"
        payload = self._store_result("skill", {
            "status": status,
            "session_id": session_id,
            "device_id": session.device_id,
            "skill_name": skill_name,
            "steps": steps,
            "command_count": len(steps),
        })
        self._record_audit(
            tool="ai_run_skill",
            source=source,
            action=self._action("skill", skill_name, RiskLevel.FLOW, device_id=session.device_id),
            status=200 if status == "success" else 409,
        )
        self._cache(source, "skill", idempotency_key, payload)
        return payload

    async def run_terminal_plan(
        self,
        *,
        session_id: str,
        steps: list[dict[str, Any]],
        total_timeout_seconds: int | float = 60,
        source: str = "desktop-api",
        kind: str = "terminal_plan",
    ) -> dict[str, Any]:
        executor = self._terminal_executor
        if executor is None:
            raise UnsupportedOperationError("Terminal plan execution is unavailable.")
        session = self._session(session_id)
        try:
            plan = parse_terminal_plan(steps, total_timeout_seconds=total_timeout_seconds)
        except TerminalPlanError as exc:
            raise UnsupportedOperationError(str(exc), details={"code": exc.code}) from exc
        result = await executor.run(
            session_id=session.id,
            device_id=session.device_id,
            plan=plan,
            owner_id=f"{kind}:{uuid4().hex}",
        )
        self._record_audit(
            tool=kind,
            source=source,
            action=self._action(kind, kind, RiskLevel.LOW, device_id=session.device_id),
            status=200 if result.get("status") == "completed" else 409,
        )
        return dict(result)

    async def run_terminal_batch(
        self,
        commands: list[str],
        *,
        session_id: str,
        command_timeout_seconds: int = 30,
        total_timeout_seconds: int | float | None = None,
        max_output_chars: int = 16_384,
        source: str = "desktop-api",
        kind: str = "terminal_batch",
    ) -> dict[str, Any]:
        executor = self._terminal_executor
        if executor is None:
            raise UnsupportedOperationError("Terminal plan execution is unavailable.")
        session = self._session(session_id)
        try:
            plan = build_batch_plan(
                commands,
                command_timeout_seconds=command_timeout_seconds,
                total_timeout_seconds=total_timeout_seconds,
                max_output_chars=max_output_chars,
            )
        except TerminalPlanError as exc:
            raise UnsupportedOperationError(str(exc), details={"code": exc.code}) from exc
        result = await executor.run(
            session_id=session.id,
            device_id=session.device_id,
            plan=plan,
            owner_id=f"{kind}:{uuid4().hex}",
        )
        self._record_audit(
            tool=kind,
            source=source,
            action=self._action(kind, kind, max((classify_command_risk(item) for item in commands), default=RiskLevel.LOW), device_id=session.device_id, command="\n".join(commands)),
            status=200 if result.get("status") == "completed" else 409,
        )
        return dict(result)

    def get_result(self, result_id: str, *, include_raw: bool = False) -> dict[str, Any]:
        with self._lock:
            result = self._results.get(result_id)
        if result is None:
            raise ResourceNotFoundError("Unknown AI result", details={"result_id": result_id})
        payload = dict(result)
        if not include_raw:
            for item in payload.get("results", []):
                if isinstance(item, dict):
                    item.pop("output", None)
            payload.pop("output", None)
        return payload

    def pending_approvals(self) -> list[dict[str, Any]]:
        return []

    def approval(self, approval_id: str) -> dict[str, Any]:
        del approval_id
        raise UnsupportedOperationError("AI approval is disabled by policy.")

    def approve(self, approval_id: str) -> dict[str, Any]:
        del approval_id
        raise UnsupportedOperationError("AI approval is disabled by policy.")

    def reject(self, approval_id: str) -> dict[str, Any]:
        del approval_id
        raise UnsupportedOperationError("AI approval is disabled by policy.")

    def audit_entries(self, limit: int = 100) -> list[dict[str, Any]]:
        with self._lock:
            return [dict(item) for item in self._audit_entries[-max(1, min(limit, 500)) :]][::-1]

    def record_mcp_audit(
        self,
        tool: str,
        params: dict[str, Any],
        *,
        status: int,
    ) -> None:
        """Record a redacted MCP boundary call, including non-AI compatibility tools."""
        command = str(params.get("command") or params.get("script") or "")
        if not command and isinstance(params.get("commands"), list):
            command = "\n".join(str(item) for item in params["commands"])
        risk = classify_command_risk(command) if command else RiskLevel.OBSERVE
        self._record_audit(
            tool=tool,
            source="mcp",
            action=self._action(
                tool,
                tool,
                risk,
                device_id=str(params.get("device_id") or ""),
                command=command,
            ),
            status=status,
        )

    def _session(self, session_id: str):
        for session in self.desktop.sessions.list_sessions():
            if session.id == session_id:
                return session
        raise ResourceNotFoundError("Unknown session", details={"session_id": session_id})

    @staticmethod
    def _action(kind: str, label: str, risk: RiskLevel, **values: Any) -> dict[str, Any]:
        return {"kind": kind, "label": label, "risk": risk.name, **values}

    def _store_result(self, kind: str, data: dict[str, Any]) -> dict[str, Any]:
        result_id = f"ai-{uuid4().hex}"
        payload = {"ok": True, "result_id": result_id, "kind": kind, **data}
        with self._lock:
            self._results[result_id] = payload
        return dict(payload)

    def _record_audit(self, *, tool: str, source: str, action: Any, status: int) -> None:
        entry = {
            "timestamp": time.time(),
            "tool": tool,
            "source": source,
            "status": status,
            "risk": getattr(getattr(action, "risk", None), "name", action.get("risk", "") if isinstance(action, dict) else ""),
            "device_id": getattr(action, "device_id", action.get("device_id", "") if isinstance(action, dict) else ""),
            "command": redact_text(getattr(action, "command", action.get("command", "") if isinstance(action, dict) else "")),
        }
        self.audit.write(entry)
        with self._lock:
            self._audit_entries.append(entry)

    def _cached(self, source: str, kind: str, key: str | None) -> dict[str, Any] | None:
        if not key:
            return None
        with self._lock:
            return dict(self._results.get(f"idem:{source}:{kind}:{key}", {})) or None

    def _cache(self, source: str, kind: str, key: str | None, value: dict[str, Any]) -> None:
        if key:
            with self._lock:
                self._results[f"idem:{source}:{kind}:{key}"] = dict(value)

    @staticmethod
    def _result_output(result: dict[str, Any]) -> str:
        return "".join(
            str(step.get("output") or "")
            for step in result.get("steps", [])
            if isinstance(step, dict)
        )[-32_768:]
