from __future__ import annotations

from dataclasses import dataclass


CURRENT_USER = "li.wei"
LOCAL_TEST_SSH_IP = "192.168.1.15"
LOCAL_TEST_SSH_USER = "lon"
LOCAL_TEST_SSH_PASSWORD = "202188"
MOCK_DEVICE_HOST = "127.0.0.1"
MOCK_DEVICE_TELNET_USER = "lon"
MOCK_DEVICE_TELNET_PASSWORD = "202188"

STATUS_OCCUPIED = "\u5df2\u88ab\u5360\u7528"
STATUS_IDLE = "\u7a7a\u95f2"
STATUS_PIPELINE = "\u6d41\u6c34\u7ebf\u5360\u7528"
STATUS_OTHER = "\u5176\u4ed6"


@dataclass(slots=True)
class Device:
    id: str
    name: str
    domain: str
    device_type: str
    cpu: str
    status: str
    owner: str | None
    ssh_ip: str
    telnet_ip: str
    username: str
    password: str
    vendor: str
    model: str
    site: str
    rack: str
    version: str
    notes: str
    ssh_port: int = 22
    telnet_port: int = 23


def sample_devices() -> list[Device]:
    return [
        Device(
            id="MOCK-LAB-000",
            name="Mock-Huawei-Lab",
            domain="测试",
            device_type="Mock Device",
            cpu="ARM-0",
            status="空闲",
            owner=None,
            ssh_ip=MOCK_DEVICE_HOST,
            telnet_ip=MOCK_DEVICE_HOST,
            username=MOCK_DEVICE_TELNET_USER,
            password=MOCK_DEVICE_TELNET_PASSWORD,
            vendor="Huawei / Mock Linux",
            model="Local Dual-Channel Lab",
            site="Localhost",
            rack="Mock-R01",
            version="Telnet:2323 / SSH:2200",
            notes="Local integration target. Device Telnet mock uses 127.0.0.1:2323 with lon/202188. Linux SSH mock uses 127.0.0.1:2200 with ops/ops123.",
            ssh_port=2200,
            telnet_port=2323,
        ),
        Device(
            id="LOCAL-SSH-001",
            name="本机测试设备",
            domain="测试",
            device_type="Local SSH",
            cpu="ARM-1",
            status="空闲",
            owner=None,
            ssh_ip=LOCAL_TEST_SSH_IP,
            telnet_ip="127.0.0.1",
            username=LOCAL_TEST_SSH_USER,
            password=LOCAL_TEST_SSH_PASSWORD,
            vendor="Microsoft OpenSSH",
            model="Windows Localhost",
            site="Local Machine",
            rack="N/A",
            version="OpenSSH_for_Windows_9.5p2",
            notes="专用于本机 SSH 联调。按 s 可直接测试连接。",
        ),
        Device(
            id="RTN-BJ-001",
            name="RTN-950A-BJ01",
            domain="\u0052\u0054\u004e",
            device_type="Microwave",
            cpu="ARM-2",
            status="\u5df2\u88ab\u5360\u7528",
            owner="li.wei",
            ssh_ip=LOCAL_TEST_SSH_IP,
            telnet_ip="172.16.1.11",
            username=LOCAL_TEST_SSH_USER,
            password=LOCAL_TEST_SSH_PASSWORD,
            vendor="Huawei",
            model="RTN 950A",
            site="Beijing Tongzhou",
            rack="A01-U08",
            version="V100R019C10",
            notes="Backhaul node for aggregation ring. SSH points to local host for testing.",
        ),
        Device(
            id="JQ-SH-003",
            name="JQ-Access-SH03",
            domain="\u4ea4\u4f01",
            device_type="Access Gateway",
            cpu="ARM-3",
            status="\u7a7a\u95f2",
            owner=None,
            ssh_ip=LOCAL_TEST_SSH_IP,
            telnet_ip="172.20.3.21",
            username=LOCAL_TEST_SSH_USER,
            password=LOCAL_TEST_SSH_PASSWORD,
            vendor="H3C",
            model="SecPath F1000",
            site="Shanghai Pudong",
            rack="B12-U16",
            version="R7608P30",
            notes="Traffic enterprise edge gateway. SSH points to local host for testing.",
        ),
        Device(
            id="RTR-GZ-006",
            name="Core-Router-GZ06",
            domain="\u8def\u7531\u5668",
            device_type="Core Router",
            cpu="ARM-4",
            status="\u6d41\u6c34\u7ebf\u5360\u7528",
            owner="pipeline.bot",
            ssh_ip=LOCAL_TEST_SSH_IP,
            telnet_ip="172.30.6.1",
            username=LOCAL_TEST_SSH_USER,
            password=LOCAL_TEST_SSH_PASSWORD,
            vendor="Cisco",
            model="ASR 1006-X",
            site="Guangzhou Tianhe",
            rack="C03-U20",
            version="IOS-XE 17.09",
            notes="Reserved by backbone pipeline validation job. SSH points to local host for testing.",
        ),
        Device(
            id="XTN-CD-002",
            name="XTN-Node-CD02",
            domain="XTN",
            device_type="Transport Node",
            cpu="ARM-5",
            status="\u7a7a\u95f2",
            owner=None,
            ssh_ip=LOCAL_TEST_SSH_IP,
            telnet_ip="172.40.2.18",
            username=LOCAL_TEST_SSH_USER,
            password=LOCAL_TEST_SSH_PASSWORD,
            vendor="Huawei",
            model="OptiXtrans XTN 980",
            site="Chengdu Hi-Tech",
            rack="D07-U11",
            version="V100R021C00",
            notes="Metro transport node with spare capacity. SSH points to local host for testing.",
        ),
        Device(
            id="RTN-SZ-009",
            name="RTN-Hop-SZ09",
            domain="\u0052\u0054\u004e",
            device_type="Microwave",
            cpu="ARM-6",
            status="\u5176\u4ed6",
            owner="li.wei",
            ssh_ip=LOCAL_TEST_SSH_IP,
            telnet_ip="172.16.9.9",
            username=LOCAL_TEST_SSH_USER,
            password=LOCAL_TEST_SSH_PASSWORD,
            vendor="Huawei",
            model="RTN 980",
            site="Shenzhen Nanshan",
            rack="E02-U05",
            version="V100R018C00",
            notes="Temporarily held for antenna alignment and field handoff. SSH points to local host for testing.",
        ),
        Device(
            id="LAB-BJ-010",
            name="Lab-Gateway-BJ10",
            domain="\u6d4b\u8bd5",
            device_type="Validation Gateway",
            cpu="ARM-7",
            status="\u7a7a\u95f2",
            owner=None,
            ssh_ip=LOCAL_TEST_SSH_IP,
            telnet_ip="172.18.10.10",
            username=LOCAL_TEST_SSH_USER,
            password=LOCAL_TEST_SSH_PASSWORD,
            vendor="Huawei",
            model="Lab GW 1000",
            site="Beijing Lab",
            rack="F01-U02",
            version="V200R001C00",
            notes="Added to expand CPU filter coverage.",
        ),
        Device(
            id="JQ-HZ-011",
            name="JQ-Edge-HZ11",
            domain="\u4ea4\u4f01",
            device_type="Edge Gateway",
            cpu="ARM-8",
            status="\u5df2\u88ab\u5360\u7528",
            owner="li.wei",
            ssh_ip=LOCAL_TEST_SSH_IP,
            telnet_ip="172.18.11.11",
            username=LOCAL_TEST_SSH_USER,
            password=LOCAL_TEST_SSH_PASSWORD,
            vendor="H3C",
            model="SecPath F5000",
            site="Hangzhou Binjiang",
            rack="F02-U08",
            version="R7801P12",
            notes="Added to expand CPU filter coverage.",
        ),
        Device(
            id="RTR-SH-012",
            name="Metro-Router-SH12",
            domain="\u8def\u7531\u5668",
            device_type="Metro Router",
            cpu="ARM-9",
            status="\u7a7a\u95f2",
            owner=None,
            ssh_ip=LOCAL_TEST_SSH_IP,
            telnet_ip="172.18.12.12",
            username=LOCAL_TEST_SSH_USER,
            password=LOCAL_TEST_SSH_PASSWORD,
            vendor="Cisco",
            model="NCS 540",
            site="Shanghai Minhang",
            rack="F03-U09",
            version="IOS-XR 7.8.1",
            notes="Added to expand CPU filter coverage.",
        ),
        Device(
            id="XTN-WH-013",
            name="XTN-Agg-WH13",
            domain="XTN",
            device_type="Transport Aggregation",
            cpu="ARM-10",
            status="\u5176\u4ed6",
            owner="ops.shift",
            ssh_ip=LOCAL_TEST_SSH_IP,
            telnet_ip="172.18.13.13",
            username=LOCAL_TEST_SSH_USER,
            password=LOCAL_TEST_SSH_PASSWORD,
            vendor="Huawei",
            model="OptiXtrans XTN 900",
            site="Wuhan Optical Valley",
            rack="F04-U10",
            version="V100R022C00",
            notes="Added to expand CPU filter coverage.",
        ),
        Device(
            id="RTN-XA-014",
            name="RTN-Link-XA14",
            domain="\u0052\u0054\u004e",
            device_type="Backhaul Radio",
            cpu="ARM-11",
            status="\u7a7a\u95f2",
            owner=None,
            ssh_ip=LOCAL_TEST_SSH_IP,
            telnet_ip="172.18.14.14",
            username=LOCAL_TEST_SSH_USER,
            password=LOCAL_TEST_SSH_PASSWORD,
            vendor="Huawei",
            model="RTN 380AX",
            site="Xian Yanta",
            rack="F05-U05",
            version="V100R017C20",
            notes="Added to expand CPU filter coverage.",
        ),
        Device(
            id="JQ-SZ-015",
            name="JQ-Branch-SZ15",
            domain="\u4ea4\u4f01",
            device_type="Branch Security Gateway",
            cpu="ARM-12",
            status="\u6d41\u6c34\u7ebf\u5360\u7528",
            owner="pipeline.bot",
            ssh_ip=LOCAL_TEST_SSH_IP,
            telnet_ip="172.18.15.15",
            username=LOCAL_TEST_SSH_USER,
            password=LOCAL_TEST_SSH_PASSWORD,
            vendor="H3C",
            model="SecPath M9000",
            site="Shenzhen Futian",
            rack="F06-U12",
            version="R7905P03",
            notes="Added to expand CPU filter coverage.",
        ),
        Device(
            id="RTR-CD-016",
            name="Core-Router-CD16",
            domain="\u8def\u7531\u5668",
            device_type="Core Router",
            cpu="ARM-13",
            status="\u7a7a\u95f2",
            owner=None,
            ssh_ip=LOCAL_TEST_SSH_IP,
            telnet_ip="172.18.16.16",
            username=LOCAL_TEST_SSH_USER,
            password=LOCAL_TEST_SSH_PASSWORD,
            vendor="Cisco",
            model="ASR 9902",
            site="Chengdu Tianfu",
            rack="F07-U15",
            version="IOS-XR 7.7.2",
            notes="Added to expand CPU filter coverage.",
        ),
        Device(
            id="LAB-GZ-017",
            name="Perf-Node-GZ17",
            domain="\u6d4b\u8bd5",
            device_type="Performance Test Node",
            cpu="ARM-14",
            status="\u5df2\u88ab\u5360\u7528",
            owner="qa.bot",
            ssh_ip=LOCAL_TEST_SSH_IP,
            telnet_ip="172.18.17.17",
            username=LOCAL_TEST_SSH_USER,
            password=LOCAL_TEST_SSH_PASSWORD,
            vendor="Dell",
            model="R740xd",
            site="Guangzhou Lab",
            rack="F08-U18",
            version="Ubuntu 22.04",
            notes="Added to expand CPU filter coverage.",
        ),
        Device(
            id="XTN-NJ-018",
            name="XTN-Hub-NJ18",
            domain="XTN",
            device_type="Transport Hub",
            cpu="ARM-15",
            status="\u5176\u4ed6",
            owner="li.wei",
            ssh_ip=LOCAL_TEST_SSH_IP,
            telnet_ip="172.18.18.18",
            username=LOCAL_TEST_SSH_USER,
            password=LOCAL_TEST_SSH_PASSWORD,
            vendor="Huawei",
            model="OptiXtrans XTN 960",
            site="Nanjing Jiangning",
            rack="F09-U07",
            version="V100R020C30",
            notes="Added to expand CPU filter coverage.",
        ),
        Device(
            id="RTR-TJ-019",
            name="Border-Router-TJ19",
            domain="\u8def\u7531\u5668",
            device_type="Border Router",
            cpu="ARM-16",
            status="\u7a7a\u95f2",
            owner=None,
            ssh_ip=LOCAL_TEST_SSH_IP,
            telnet_ip="172.18.19.19",
            username=LOCAL_TEST_SSH_USER,
            password=LOCAL_TEST_SSH_PASSWORD,
            vendor="Juniper",
            model="MX204",
            site="Tianjin Binhai",
            rack="F10-U04",
            version="Junos 22.3R1",
            notes="Added to expand CPU filter coverage.",
        ),
    ]
