"""Workspace theme tokens shared by Python-rendered UI surfaces."""

from __future__ import annotations

WORKSPACE_BG = "#020617"
WORKSPACE_PANEL = "#0f172a"
WORKSPACE_PANEL_RAISED = "#111c2f"
WORKSPACE_INPUT = "#08101d"
WORKSPACE_LINE = "#243244"
WORKSPACE_LINE_STRONG = "#334155"
WORKSPACE_TEXT = "#f8fafc"
WORKSPACE_MUTED = "#a7b4c7"
WORKSPACE_SOFT = "#718096"
WORKSPACE_ACCENT = "#22c55e"
WORKSPACE_BLUE = "#60a5fa"
WORKSPACE_WARN = "#fbbf24"
WORKSPACE_DANGER = "#f87171"
WORKSPACE_SUCCESS_TEXT = "#d8fff0"
WORKSPACE_DANGER_TEXT = "#fecaca"
WORKSPACE_WARN_TEXT = "#f8e7a1"
WORKSPACE_SELECTED = "#24324a"
WORKSPACE_TEXT_SELECTION_BG = "#315f9f"
WORKSPACE_TEXT_SELECTION_FG = "#f8fafc"
WORKSPACE_SCROLL_HOVER = "#475569"

WORKSPACE_SUCCESS_SOFT = "rgba(34, 197, 94, 0.14)"
WORKSPACE_SUCCESS_LINE = "rgba(34, 197, 94, 0.42)"
WORKSPACE_WARNING_SOFT = "rgba(251, 191, 36, 0.13)"
WORKSPACE_WARNING_LINE = "rgba(251, 191, 36, 0.42)"
WORKSPACE_NEUTRAL_SOFT = "rgba(113, 128, 150, 0.14)"
WORKSPACE_NEUTRAL_LINE = "rgba(113, 128, 150, 0.36)"


# ---------------------------------------------------------------------------
# Dark → light (晨光) token mapping.
#
# Every distinct hex/rgba literal in `APP_STYLE` (src/styles.py) and
# `workspace-theme.css` must appear as a key here so the light stylesheet
# generated by Task 2 cannot leak a stray dark literal.  Light values follow
# the luminance inversion principle:
#   - surfaces get lighter, text gets darker;
#   - semantic accents (green/blue/amber/danger) deepen so they stay readable
#     on light backgrounds;
#   - text > muted > soft luminance hierarchy is preserved.
# ---------------------------------------------------------------------------

DARK_TO_LIGHT: dict[str, str] = {
    # -- base surfaces ------------------------------------------------
    "#020617": "#f2f4f6",   # --bg
    "#0f172a": "#ffffff",   # --panel
    "#111c2f": "#e8ebef",   # --panel-2 / raised
    "#08101d": "#fafbfc",   # --input
    "#24324a": "#dbe6f2",   # --selected
    # -- borders -------------------------------------------------------
    "#243244": "#d5dae1",   # --line
    "#334155": "#c0c7d1",   # --line-strong
    "#475569": "#aeb6c2",   # --scroll-hover
    # -- text ----------------------------------------------------------
    "#f8fafc": "#1c2128",   # --text
    "#a7b4c7": "#5a6470",   # --muted
    "#718096": "#87919d",   # --soft
    # -- accents --------------------------------------------------------
    "#22c55e": "#1f8a4c",   # --accent
    "#60a5fa": "#3a7ecf",   # --accent-2 / --blue
    "#fbbf24": "#b7791f",   # --warn
    "#f87171": "#c74a4a",   # --danger
    # -- text-selection -------------------------------------------------
    "#315f9f": "#3a7ecf",   # --text-selection-bg
    # -- dark base surfaces (all dark literals in APP_STYLE) -----------
    "#05080c": "#f5f7f9",
    "#06090d": "#f4f6f8",
    "#070707": "#f6f7f9",
    "#070b10": "#f6f8fa",
    "#071611": "#e9f4ed",
    "#080808": "#f2f4f6",
    "#090d12": "#f3f5f7",
    "#090e13": "#f4f6f8",
    "#090f15": "#f5f7f9",
    "#0a0a0a": "#f5f6f8",
    "#0a0f15": "#f6f8fa",
    "#0b0f14": "#f3f5f7",
    "#0b1016": "#f5f7f9",
    "#0b1117": "#f5f7f9",
    "#0b1118": "#f4f6f8",
    "#0b1219": "#f3f5f7",
    "#0b141d": "#f2f4f6",
    "#0b1525": "#e9eef5",
    "#0c1218": "#f4f6f8",
    "#0e0e0e": "#f5f7f9",
    "#0f141a": "#f2f4f6",
    "#0f161d": "#f2f4f6",
    "#10161d": "#f1f3f5",
    "#101820": "#eff1f4",
    "#101915": "#edf5ef",
    "#101b2b": "#e8edf4",
    "#102019": "#e2f1e8",
    "#111111": "#eef0f3",
    "#111820": "#eef0f3",
    "#111821": "#eef1f4",
    "#111b25": "#ecf0f5",
    "#121212": "#eef0f3",
    "#121820": "#ecedf0",
    "#131920": "#eceef1",
    "#141414": "#fbfcfd",
    "#141a21": "#ebedf0",
    "#151b22": "#eaedf0",
    "#152033": "#e4ebf3",
    "#15212e": "#ebeff3",
    "#161616": "#e9ebee",
    "#161d26": "#e8ebef",
    "#171d24": "#e7eaed",
    "#171e26": "#e7eaee",
    "#17212c": "#e6e9ed",
    "#172236": "#dfe6ef",
    "#181818": "#e8eaed",
    "#181d24": "#e6e9ec",
    "#181f27": "#e5e8ec",
    "#18212b": "#e4e7eb",
    "#1a1a1a": "#e3e6ea",
    "#1a2028": "#e3e7eb",
    "#1a222c": "#e2e6ea",
    "#1a2531": "#e1e6ec",
    "#1b222b": "#e1e4e8",
    "#1b232d": "#e1e4e8",
    "#1b242e": "#e0e4e8",
    "#1b2a38": "#dee5ee",
    "#1c1c1c": "#e2e5e9",
    "#1c242e": "#dfe3e7",
    "#1d2630": "#dee3e8",
    "#1d2a38": "#dce4ed",
    "#1d2b38": "#dce4ed",
    "#1e1e1e": "#e0e3e7",
    "#1e293b": "#dbe2ec",
    "#1e3a5f": "#cfe0f2",
    "#202731": "#dde1e5",
    "#202832": "#dce0e4",
    "#202a36": "#dbe3ea",
    "#222222": "#dfe2e6",
    "#222a33": "#dbe0e5",
    "#222a34": "#dadfe4",
    "#233548": "#d3dce8",
    "#243044": "#d6dee9",
    "#243241": "#d5dce5",
    "#252526": "#dbe0e5",
    "#252c35": "#d9dee4",
    "#253140": "#d6dde6",
    "#253444": "#d4dbe4",
    "#262626": "#c8ced6",
    "#262f39": "#d5dbe1",
    "#263544": "#d3dbe4",
    "#264f78": "#c6d8eb",
    "#273242": "#d4dbe3",
    "#273747": "#d3dbe3",
    "#274052": "#d0d9e3",
    "#283747": "#d2dae3",
    "#2a2a2a": "#d7dade",
    "#2a2d2e": "#d5d8da",
    "#2a3644": "#cfd7e0",
    "#2b2b2b": "#d6d9dd",
    "#2b4252": "#cbd6e0",
    "#2c333d": "#d3d7dc",
    "#2d3a49": "#cfd7e0",
    "#2f3744": "#d1d5da",
    "#2f4050": "#ccd5de",
    "#303842": "#d0d5da",
    "#303945": "#cfd4d9",
    "#303d4d": "#cbd3dc",
    "#363f4a": "#ccd2d8",
    "#373f4a": "#cbd1d7",
    "#3a424d": "#cbd1d7",
    "#3b4450": "#c7ced5",
    "#3c3c3c": "#c9cdd2",
    "#3f5267": "#b9c6d6",
    "#404040": "#c7cbd0",
    "#464e59": "#c0c7cf",
    "#4a525e": "#bdc4cc",
    "#4a535e": "#bcc3cb",
    "#506174": "#aeb9c7",
    "#525b66": "#b4bbc3",
    "#526176": "#a9b5c3",
    "#5a626e": "#adb5be",
    "#64748b": "#9aa4b0",
    # -- neutral text / soft grays (light → dark on light theme) --------
    "#6f8194": "#6a7c92",
    "#7f8b99": "#5f6b78",
    "#7f8c9b": "#7b8691",
    "#7f92a6": "#77879a",
    "#8894a3": "#6f7a87",
    "#8b98a8": "#6c7785",
    "#8ea7c2": "#6d86a0",
    "#8f9dad": "#66717e",
    "#8fa0b7": "#68819c",
    "#8fa1b4": "#697c92",
    "#94a0ae": "#616d79",
    "#96a6b8": "#5f7389",
    "#9aa7b6": "#5f6b78",
    "#9fb0c2": "#5a6d83",
    "#a0a0a0": "#5a6470",
    "#a8b5c4": "#57626f",
    "#b8c7d9": "#4f6176",
    "#bdbdbd": "#4d575f",
    "#c0c0c0": "#454f58",
    "#c3d3e4": "#425d78",
    "#c5d5e6": "#3e5a75",
    "#cbd5e1": "#3a424d",
    "#cccccc": "#3f474f",
    "#d0d0d0": "#3a424b",
    "#d5dee9": "#333d47",
    "#d6deeb": "#313c48",
    "#dce3eb": "#333d47",
    "#e5edf6": "#232d37",
    "#e8edf3": "#222c35",
    "#ededed": "#1a1f26",
    "#f2f5f8": "#242e38",
    "#f7f9fb": "#2a333c",
    "#f8fbff": "#1b2430",
    "#fafafa": "#23282e",
    "#ffffff": "#1c2128",
    # -- semantic greens (deepen for light) -----------------------------
    "#163326": "#d8ebe0",
    "#15803d": "#1a7f45",
    "#16a34a": "#1a7f45",
    "#166534": "#1d6d3c",
    "#4ade80": "#22a85c",
    "#10b981": "#0ea871",
    "#3cc98e": "#1fa872",
    "#2b6049": "#5c9c7c",
    "#2f7d5b": "#3f9a71",
    "#315042": "#6fa98b",
    "#3b7a5d": "#57a37f",
    "#b7e4cf": "#1f9b65",
    "#d1fae5": "#157c48",
    "#d8fff0": "#15824a",
    "#f0fdf4": "#f7fbf8",
    # -- semantic blues / indigos ----------------------------------------
    "#3a3f6b": "#cfd3ea",
    "#3b82f6": "#2f6fc8",
    "#4a5dd4": "#3f51c8",
    "#4f7cff": "#3f6fe0",
    "#49627d": "#8fa9c0",
    "#5b6ef5": "#4d5fd9",
    "#6d7ff7": "#5f70e3",
    "#8d9aff": "#4d5fdd",
    "#007acc": "#0f6fc0",
    "#d8e4f5": "#2e4a6b",
    "#dce6f1": "#2f4a69",
    "#e7f1ff": "#22314a",
    "#edf5ff": "#1f2c3f",
    # -- semantic amber / warn -------------------------------------------
    "#f59e0b": "#b97912",
    "#f5a623": "#b98316",
    # -- semantic danger / reds ------------------------------------------
    "#2d1215": "#f3d6d8",
    "#3d181c": "#edc9cc",
    "#450a0a": "#f7cbcb",
    "#34181d": "#f0d6d8",
    "#4a1f23": "#ecc7ca",
    "#5c2328": "#c98f92",
    "#5f1717": "#e8b6b8",
    "#606060": "#8f989f",
    "#732a30": "#c3868b",
    "#7f1d1d": "#e59c9f",
    "#8f2f3a": "#c4686f",
    "#ef4444": "#d63a3a",
    "#f04f5a": "#d63a4a",
    "#fb7185": "#d6485c",
    "#f88b91": "#d0454c",
    "#fecaca": "#c64747",
    "#fee2e2": "#d54a4a",
    # -- legacy Linear/Vercel palette (kept so APP_STYLE maps cleanly) ---
    "#0c0c0c": "#ffffff",
    "#333333": "#aab2bd",
    "#808080": "#6a737e",
    "#707070": "#8a939e",
    "#4d4d4d": "#a0a8b2",
    # -- workspace-theme.css-only hexes (not in APP_STYLE) ---------------
    "#050b14": "#f5f7f9",
    "#86efac": "#1f9b65",
    "#91d7e3": "#3b8ba0",
    "#b5eff7": "#2f8fa6",
    "#b7c8ff": "#3f5cc8",
    "#c4b5fd": "#6b56d6",
    "#ddd6fe": "#6b56d6",
    "#f5d99a": "#a87a1f",
    "#f6f8fb": "#232c36",
    "#f8e7a1": "#a87a1f",
    "#fca5a5": "#d0454c",
    # -- status soft/line rgba (dark) → light equivalents ----------------
    "rgba(34, 197, 94, 0.14)": "rgba(31, 138, 76, 0.12)",
    "rgba(34, 197, 94, 0.42)": "rgba(31, 138, 76, 0.38)",
    "rgba(251, 191, 36, 0.13)": "rgba(183, 121, 31, 0.14)",
    "rgba(251, 191, 36, 0.42)": "rgba(183, 121, 31, 0.38)",
    "rgba(96, 165, 250, 0.13)": "rgba(58, 126, 207, 0.13)",
    "rgba(96, 165, 250, 0.42)": "rgba(58, 126, 207, 0.38)",
    "rgba(113, 128, 150, 0.14)": "rgba(135, 145, 157, 0.16)",
    "rgba(113, 128, 150, 0.36)": "rgba(135, 145, 157, 0.32)",
    # -- APP_STYLE translucent surface rgba --------------------------------
    "rgba(15, 23, 42, 0.66)": "rgba(255, 255, 255, 0.66)",
    "rgba(15, 23, 42, 0.72)": "rgba(255, 255, 255, 0.72)",
    "rgba(15, 23, 42, 0.78)": "rgba(255, 255, 255, 0.78)",
    "rgba(17, 28, 47, 0.78)": "rgba(232, 235, 239, 0.78)",
    "rgba(8, 16, 29, 0.72)": "rgba(250, 251, 252, 0.72)",
    "rgba(8, 16, 29, 0.78)": "rgba(250, 251, 252, 0.78)",
    # -- workspace-theme.css translucent rgba ------------------------------
    "rgba(0, 0, 0, 0.5)": "rgba(0, 0, 0, 0.12)",
    "rgba(127, 29, 29, 0.25)": "rgba(198, 71, 71, 0.18)",
    "rgba(13, 17, 23, 0.94)": "rgba(242, 244, 246, 0.94)",
    "rgba(167, 180, 199, 0.68)": "rgba(90, 100, 112, 0.68)",
    "rgba(2, 6, 23, 0.72)": "rgba(242, 244, 246, 0.72)",
    "rgba(248, 113, 113, 0.6)": "rgba(199, 74, 74, 0.6)",
    "rgba(34, 197, 94, 0.08)": "rgba(31, 138, 76, 0.08)",
    "rgba(34, 197, 94, 0.62)": "rgba(31, 138, 76, 0.5)",
    "rgba(36, 50, 68, 0.62)": "rgba(213, 218, 225, 0.62)",
    "rgba(8, 12, 17, 0.92)": "rgba(250, 251, 252, 0.92)",
    "rgba(8, 16, 29, 0.55)": "rgba(250, 251, 252, 0.55)",
    "rgba(9, 12, 16, 0.86)": "rgba(243, 245, 247, 0.86)",
    "rgba(96, 165, 250, 0.10)": "rgba(58, 126, 207, 0.10)",
    "rgba(96, 165, 250, 0.22)": "rgba(58, 126, 207, 0.22)",
    "rgba(96, 165, 250, 0.35)": "rgba(58, 126, 207, 0.35)",
}


def qwebengine_background_stylesheet(object_name: str) -> str:
    """Return the standard transparent-border WebEngine background rule."""
    return f"QWebEngineView#{object_name} {{ background: {WORKSPACE_BG}; border: 0; }}"
